app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path

admin_url = settings.ADMIN_URL

custom_apps = settings.CUSTOM_APPS

utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = f'{utils_path}.views.handler400'

handler403 = f'{utils_path}.views.handler403'

handler404 = f'{utils_path}.views.handler404'

handler500 = f'{utils_path}.views.handler500'

urlpatterns = [
    path(admin_url, admin.site.urls),
    re_path(
        r"^sitemap.xml",
        sitemap,
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view()
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view()
    ),
    path(
        "ckeditor5/",
        include('django_ckeditor_5.urls')
    ),
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
    path(
        '',
        include(apps_urls)
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/project/page/features/ai_features/urls.py
from django.urls import include, path
from .views import AIFeaturesTemplateView

app_name = "ai_features"

urlpatterns = [
    path(
        'features/AI',
        AIFeaturesTemplateView.as_view(),
        name='home'
    )
]

apps/project/page/features/automation_features/urls.py
from django.urls import path

from .views import AutomationFeaturesTemplateView

app_name = "automation_features"

urlpatterns = [
    path(
        'features/automation',
        AutomationFeaturesTemplateView.as_view(),
        name='home'
    )
]

apps/project/page/index/urls.py
from django.urls import path

from .views import (
    IndexTemplateView,
    SubscribeNewsLetterFormView,
    UnsubscribeView
)

app_name = "index"

urlpatterns = [
    path(
        '',
        IndexTemplateView.as_view(),
        name='home'
    ),
    path(
        'newsletter',
        SubscribeNewsLetterFormView.as_view(),
        name='newsletter'
    ),
    path(
        'unsuscribe/<uuid:unique_id>/',
        UnsubscribeView.as_view(),
        name='unsubscribe'
    )
]

apps/project/page/index/templates/includes/footer.html
{% load static i18n %}

<footer class="footer">
    <div class="footer__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <a class="logo" href="/">
                    <img
                        alt="Booking Logo"
                        src="https://sebasmoralesd.com/rms/public/static/imgs/favicon/favicon.png"
                        style="max-height: 200px;"
                    />
                    </a>
                    <address>
                    <p>
                        Colombia
                        <br />
                        Antioquia, Medellín
                    </p>
                    <p>
                        <a href="mailto:info@sebasmoralesd.com">
                        <small>info@sebasmoralesd.com</small>
                        </a>
                    </p>
                    <p>
                        <a href="tel:+573507039698">
                        <small>+57 350 703 96 98</small>
                        </a>
                    </p>
                    <p>
                        <a href="tel:+573014883466">
                        <small>+57 301 488 34 66</small>
                        </a>
                    </p>
                    </address>
                </div>
                <div class="col-lg-7">
                    <div class="row">
                    <div class="col-lg-3">
                        <div class="footer__title">{% trans 'Company:' %}</div>
                        <nav class="footer__list">
                        <ul>
                            <li><a href="/">{% trans 'About Us' %}</a></li>
                            <li><a href="/">{% trans 'Terms of Use' %}</a></li>
                            <li><a href="/">{% trans 'Privacy Policy' %}</a></li>
                        </ul>
                        </nav>
                    </div>

                    <div class="col-lg-9">
                        <nav class="footer__social">
                            <a
                                href=""
                                target="_blank"
                            >
                                <i class="fab fa-facebook"></i>
                            </a>
                            <a
                                href=""
                                target="_blank"
                            >
                                <i class="fab fa-instagram"></i>
                            </a>
                            <a
                                href=""
                                target="_blank"
                            >
                                <i class="fab fa-youtube"></i>
                            </a>
                            <a
                                href=""
                                target="_blank"
                            >
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                            <a
                                href=""
                                target="_blank"
                            >
                                <i class="fab fa-twitter"></i>
                            </a>
                        </nav>
                        {% include 'includes/footer/form.html' %}
                    </div>
                    <p class="footer__form-text">
                        {% blocktrans %}
                            We send a monthly email with announcements, tips, news,
                            feature updates, and important info. We'll only e-mail you
                            if it's important.
                        {% endblocktrans %}
                    </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer__bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <p>All rights reserved © {% now "Y" %} - Sebastián Morales</p>
                </div>
            </div>
        </div>
    </div>
</footer>

apps/project/page/index/templates/includes/nav.html
{% load static i18n %}

{% get_current_language as LANGUAGE_CODE %}

{% get_available_languages as LANGUAGES %}

<nav class="navigation">
    <ul>
        <li>
            <a href="{% url 'index:home' %}">
                {% trans 'HOME' %}
            </a>
        </li>
        <li>
            <a class="navigation-dropdown__click">
                {% trans 'FEATURES' %}
            </a>
            <span class="navigation-dropdown__trigger">
                <i class="fas fa-chevron-down"></i>
            </span>
            <div class="navigation-dropdown">
                <ul>
                    <!-- <li>
                        <a href="/">
                            {% trans 'CORE FEATURES' %}
                        </a>
                    </li> -->
                    <li>
                        <a href="{% url 'ai_features:home' %}">
                            {% trans 'ARTIFICIAL INTELLIGENCE' %}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'automation_features:home' %}">
                            {% trans 'AUTOMATIC DATA PROCESSING' %}
                        </a>
                    </li>
                    <!-- <li>
                        <a href="/">
                            {% trans 'PMS INTEGRATION' %}
                        </a>
                    </li> -->
                </ul>
            </div>
        </li>
        <!-- <li>
            <a href="/">
                {% trans 'PRICING' %}
            </a>
        </li> -->
        <!-- <li>
            <a class="navigation-dropdown__click">
                {% trans 'RESOURCES' %}
            </a>
            <span class="navigation-dropdown__trigger">
                <i class="fas fa-chevron-down"></i>
            </span>
            <div class="navigation-dropdown">
                <ul>
                    <li>
                        <a href="/">
                            {% trans 'CLIENT PORTAL' %}
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            {% trans 'BLOG' %}
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            {% trans 'FAQS' %}
                        </a>
                    </li>
                    <li>
                        <a href="/">
                            {% trans 'CUSTOMER STORIES' %}
                        </a>
                    </li>
                </ul>
            </div>
        </li> -->
        <!-- <li>
            <a href="/">
                {% trans 'ABOUT US' %}
            </a>
        </li> -->
        <li class="navigation__lang">
            <a class="navigation-dropdown__click">
                <i class="flag {% if LANGUAGE_CODE == 'es' %}flag-colombia{% else %}flag-united-states{% endif %}"></i>
                <span>{% if LANGUAGE_CODE == 'es' %}Español{% else %}English{% endif %}</span>
            </a>
            <span class="navigation-dropdown__trigger">
                <i class="fas fa-chevron-down"></i>
            </span>
            <div class="navigation-dropdown">
                <ul>
                    <li>
                        <a href="{% url 'set_language' %}?lang={% if LANGUAGE_CODE == 'es' %}en{% else %}es{% endif %}">
                            <i class="flag {% if LANGUAGE_CODE == 'es' %}flag-united-states{% else %}flag-colombia{% endif %}"></i>
                            {% if LANGUAGE_CODE == 'es' %}English{% else %}Español{% endif %}
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <!-- <li class="navigation__item-button navigation__item--mobile">
            <a href="/" class="button-orange">
                {% trans 'REQUEST A PLAYGROUND' %}
            </a>
        </li> -->
        <!-- <li class="navigation__item-button navigation__item--mobile">
            <a href="/" class="button-orange">
                {% trans 'SCHEDULE A MEETING' %}
            </a>
        </li> -->
    </ul>
</nav>